### ISSUE TITLE
More so a request than an issue (first time using GitHub, sorry if this is the wrong spot), would it be possible to enable functionality to allow for the level archive folder & RPCS3 savedata folder to be set via a command line input?

### ISSUE THREAD

**Issue by PerryTute** [WaleedAlassaf/LittleBigSearch#1]
The idea is that the user could create a simple batch script to launch the application, with a couple of launch arguments, establishing the aforementioned folder locations (preferably at a relative path to the "LittleBigSearch" executable, rather than an absolute path), to allow for a more portable approach.

**Comment by uualid** [comment]
Great idea 👍 I'll look into that when I have time to work on this app.

**Comment by uualid** [comment]
I just released a new version for the app with the ability to save the paths to an external JSON file which achieve the same goal here  👍. I might add a way to manage multiple archives file for LBP1, 2, and 3  to switch between them inside the app UI later on.
