### ISSUE TITLE
Suggestion: Clear levels from destination folder

### ISSUE THREAD

**Issue by JohnGhostly** [WaleedAlassaf/LittleBigSearch#6]
I wish I knew about this tool prior to downloading the archive, I have no idea how to clear out pre-existing levels in my data folder so would it be possible to implement a feature to clear it out?

**Comment by uualid** [comment]
You can use the tool to clear individual level folders. If you mean clear out all the level folders you can also use the tool to open the destination file and do a Ctrl+A to select all folders then delete them all or move them.
