### ISSUE TITLE
The Destination Folder window from clicking the Hearted button is always empty

### ISSUE THREAD

**Issue by reecespieces** [WaleedAlassaf/LittleBigSearch#7]
I can search for the same term and click the level again, and it will remove it from my destination folder, but the Hearted section in the program is always empty.

It would be nice if the Hearted button could show me all the levels that are currently in the destination folder.

**Comment by uualid** [comment]
Are you running 1.1.4 windows version ? I'm not able to recreate the bug that you're descripting. Hearted window always shows all the levels inside the destination folder. if you can upload a video of this bug it will help me investigate it.

**Comment by uualid** [comment]
I think I was able to recreate the bug, I believe some corrupted level files might be causing the issue. can you confirm that by making a new empty destination folder on your desktop for testing and set it inside the app. 

see if the behavior is fixed now by hearting some levels. if it starts working normally please send me your problematic destination folder so I can add some error handling for these sort of corruptions. make sure it is the exact file referred in the settings window. 

Thank you for reporting this!

**Comment by reecespieces** [comment]
It works with the test destination folder on the desktop.

The destination folder I'm using is the savedata folder in RPCS3, and it does have other PS3 saves in it from other games too.

If I just make a new folder in that folder and set that as the destination, then it all works as it should as well, just like it did with the folder on the desktop,

It would be nice if it could just only look at folders that start with the same GameID as the folders in the selected archive.

Like in my current use case, it really just needs to look at folders starting with BCUS98148LEVEL (since I am using the archive for the USA version of the original copy of LittleBigPlanet1).

**Comment by reecespieces** [comment]
[savedata.zip](https://github.com/WaleedAlassaf/LittleBigSearch/files/10190536/savedata.zip)

Example of a destination folder that doesn't work. It has a LBP1 save, a LBP1 level, and 2 other saves from unrelated games.

**Comment by uualid** [comment]
The app will now check if the files are related to LittleBigPlanet before trying to build a level cell. You can get the patched version from [here](https://github.com/WaleedAlassaf/LittleBigSearch/releases/tag/1.1.4.1)

Thank you for reporting this bug as I wasn't aware of it becaue I only used RPCS3 for LBP games. If you encountered any other bugs please report them here.

**Comment by reecespieces** [comment]
It works now, but save data and profile data from the LitttleBigPlanet games shows up in the list too.

![Capture](https://user-images.githubusercontent.com/15993751/206814592-73b62c40-4d74-4d1a-9354-9ccb841bff84.PNG)


It would be nice if those didn't show there, so it only shows levels.

**Comment by uualid** [comment]
You're right I should let the app ignore these files.
