### ISSUE TITLE
LBP3 level crashes and download level failed: https://zaprit.fish/slot/100430748

### ISSUE THREAD

**Issue by JoJoApCo** [WaleedAlassaf/LittleBigSearch#9]
Title: Basically Every LBP3 Story Prize and some DLC (Over 900 items!)
PSN user: lbphaxmods
LBP Search url: https://zaprit.fish/slot/100430748
Hash: 16dc3f51256216460067d14d93ea95261bf36064
![capture 1](https://github.com/user-attachments/assets/910282dd-007e-40c5-9a9b-65ccd0e58ae1)
![Capture 2](https://github.com/user-attachments/assets/d7362223-a22a-417a-b51f-d540199c8f11)

**Comment by uualid** [comment]
This tool is not related to LittleBigSearch.
